#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: ingress-nginx
#  annotations:
##    kubernetes.io/ingress.global-static-ip-name: "ingress-static-ip" # 고정IP 이름
#    networking.gke.io/managed-certificates: "gcpzg-cert"
#    kubernetes.io/ingress.class: "gce"
#spec:
#  rules:
#    - http:
#        paths:
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: nginx
#                port:
#                  number: 80