apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/backend-config: '{"ports": {"8080":"vets-be"}}'
  name: vets-service
  labels:
    app: spring-petclinic
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: spring-petclinic
    tier: vets
